// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"douyin/app/service/video/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CORSMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/feed",
					Handler: FeedHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CORSMiddleware, serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/publish/action",
					Handler: PublishHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/publish/list",
					Handler: GetPublishListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/favorite/action",
					Handler: FavoriteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/favorite/list",
					Handler: GetFavoriteListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/comment/action",
					Handler: CommentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/comment/list",
					Handler: GetCommentListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin"),
	)
}
