// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"douyin/app/service/auth/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/token/auth",
				Handler: GetTokenByAuthHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/token/read",
				Handler: ReadTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
