// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"douyin/app/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CORSMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/register",
					Handler: RegisterHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/login",
					Handler: LoginHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CORSMiddleware, serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user",
					Handler: ProfileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/relation/action",
					Handler: RelationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/relation/follow/list",
					Handler: GetFollowListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/relation/follower/list",
					Handler: GetFollowerListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/relation/friend/list",
					Handler: GetFriendListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin"),
	)
}
