// Code generated by goctl. DO NOT EDIT.
package types

type Profile struct {
	Id              int64  `json:"id"`               // 用户id
	Name            string `json:"name"`             // 用户名称
	FollowCount     int64  `json:"follow_count"`     // 关注总数
	FollowerCount   int64  `json:"follower_count"`   // 粉丝总数
	IsFollow        bool   `json:"is_follow"`        // true-已关注，false-未关注
	Avatar          string `json:"avatar"`           // 头像
	BackgroundImage string `json:"background_image"` // 背景大图
	Signature       string `json:"signature"`        // 简介
	TotalFavorited  int64  `json:"total_favorited"`  // 获赞数量
	WorkCount       int64  `json:"work_count"`       // 作品总数
	FavoriteCount   int64  `json:"favorite_count"`   // 喜欢总数
}

type RegisterReq struct {
	Username string `form:"username"` // 注册用户名，最长32个字符
	Password string `form:"password"` // 密码，最长32个字符
}

type RegisterRes struct {
	StatusCode uint32 `json:"status_code"`       // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg"`        // 返回状态描述
	UserId     int64  `json:"user_id,omitempty"` // 用户id
	Token      string `json:"token,omitempty"`   // 用户鉴权token
}

type LoginReq struct {
	Username string `form:"username"` // 登录用户名
	Password string `form:"password"` // 密码
}

type LoginRes struct {
	StatusCode uint32 `json:"status_code"`       // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg"`        // 返回状态描述
	UserId     int64  `json:"user_id,omitempty"` // 用户id
	Token      string `json:"token,omitempty"`   // 用户鉴权token
}

type GetProfileReq struct {
	UserId string `form:"user_id"` // 用户id
	Token  string `form:"token"`   // 用户鉴权token
}

type GetProfileRes struct {
	StatusCode uint32   `json:"status_code"`    // 状态码，0-成功，其他值-失败
	StatusMsg  string   `json:"status_msg"`     // 返回状态描述
	User       *Profile `json:"user,omitempty"` // 用户信息
}

type RelationReq struct {
	Token      string `form:"token"`       // 用户鉴权token
	ToUserId   string `form:"to_user_id"`  // 对方用户id
	ActionType string `form:"action_type"` // 1-关注，2-取消关注
}

type RelationRes struct {
	StatusCode uint32 `json:"status_code"` // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg"`  // 返回状态描述
}

type GetFollowListReq struct {
	UserId string `form:"user_id"` // 用户id
	Token  string `form:"token"`   // 用户鉴权token
}

type GetFollowListRes struct {
	StatusCode uint32      `json:"status_code"`         // 状态码，0-成功，其他值-失败
	StatusMsg  string      `json:"status_msg"`          // 返回状态描述
	UserList   interface{} `json:"user_list,omitempty"` // 用户信息列表
}

type GetFollowerListReq struct {
	UserId string `form:"user_id"` // 用户id
	Token  string `form:"token"`   // 用户鉴权token
}

type GetFollowerListRes struct {
	StatusCode uint32      `json:"status_code"`         // 状态码，0-成功，其他值-失败
	StatusMsg  string      `json:"status_msg"`          // 返回状态描述
	UserList   interface{} `json:"user_list,omitempty"` // 用户列表
}

type GetFriendListReq struct {
	UserId string `form:"user_id"` // 用户id
	Token  string `form:"token"`   // 用户鉴权token
}

type GetFriendListRes struct {
	StatusCode uint32      `json:"status_code"`         // 状态码，0-成功，其他值-失败
	StatusMsg  string      `json:"status_msg"`          // 返回状态描述
	UserList   interface{} `json:"user_list,omitempty"` // 用户列表
}
