// Code generated by goctl. DO NOT EDIT.
package types

type Profile struct {
	Id            uint64 `json:"id"`
	Name          string `json:"name"`
	FollowCount   uint64 `json:"follow_count"`
	FollowerCount uint64 `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}

type RegisterReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type RegisterRes struct {
	StatusCode uint32 `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	UserId     uint64 `json:"user_id"`
	Token      string `json:"token"`
}

type LoginReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type LoginRes struct {
	StatusCode uint32 `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	UserId     uint64 `json:"user_id"`
	Token      string `json:"token"`
}

type ProfileReq struct {
	UserId string `form:"user_id"`
	Token  string `form:"token"`
}

type ProfileRes struct {
	StatusCode uint32  `json:"status_code"`
	StatusMsg  string  `json:"status_msg"`
	User       Profile `json:"user"`
}

type RelationReq struct {
	Token      string `form:"token"`
	ToUserId   string `form:"to_user_id"`
	ActionType string `form:"action_type"`
}

type RelationRes struct {
	StatusCode uint32 `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type GetFollowListReq struct {
	UserId string `form:"user_id"`
	Token  string `form:"token"`
}

type GetFollowListRes struct {
	StatusCode uint32     `json:"status_code"`
	StatusMsg  string     `json:"status_msg"`
	UserList   []*Profile `json:"user_list"`
}

type GetFollowerListReq struct {
	UserId string `form:"user_id"`
	Token  string `form:"token"`
}

type GetFollowerListRes struct {
	StatusCode uint32     `json:"status_code"`
	StatusMsg  string     `json:"status_msg"`
	UserList   []*Profile `json:"user_list"`
}

type GetFriendListReq struct {
	UserId string `form:"user_id"`
	Token  string `form:"token"`
}

type GetFriendListRes struct {
	StatusCode uint32     `json:"status_code"`
	StatusMsg  string     `json:"status_msg"`
	UserList   []*Profile `json:"user_list"`
}
