// Code generated by goctl. DO NOT EDIT.
package types

type Message struct {
	Id         int64  `json:"id"`
	Content    string `json:"content"`
	CreateTime string `json:"create_time"`
}

type SendMessageReq struct {
	Token      string `form:"token"`
	ToUserId   string `form:"to_user_id"`
	ActionType string `form:"action_type"`
	Content    string `form:"content,optional"`
}

type SendMessageRes struct {
	StatusCode uint32 `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type GetMessageListReq struct {
	Token    string `form:"token"`
	ToUserId string `form:"to_user_id"`
}

type GetMessageListRes struct {
	StatusCode  uint32      `json:"status_code"`
	StatusMsg   string      `json:"status_msg"`
	MessageList interface{} `json:"message_list,omitempty"`
}
