// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"douyin/app/service/chat/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CORSMiddleware, serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/message/action",
					Handler: SendMessageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/message/chat",
					Handler: GetMessageListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin"),
	)
}
