// Code generated by goctl. DO NOT EDIT.
package types

type GetTokenByAuthReq struct {
	Authorization string `header:"Authorization"`
	Obj           string `form:"obj"`
}

type GetTokenByAuthResData struct {
	Token interface{} `json:"token"`
}

type GetTokenByAuthRes struct {
	Code uint32                `json:"code"`
	Msg  string                `json:"msg"`
	Data GetTokenByAuthResData `json:"data"`
}

type ReadTokenReq struct {
	TokenValue string `form:"token_value"`
}

type ReadTokenResData struct {
	Payload string `json:"payload"`
}

type ReadTokenRes struct {
	Code uint32           `json:"code"`
	Msg  string           `json:"msg"`
	Data ReadTokenResData `json:"data"`
}
