// Code generated by goctl. DO NOT EDIT.
package types

type GetTokenByAuthReq struct {
	Authorization string `header:"Authorization"`
	Obj           string `form:"obj"`
}

type GetTokenByAuthResData struct {
	Oauth2Token interface{} `json:"oauth2_token"`
}

type GetTokenByAuthRes struct {
	Code uint32                `json:"code"`
	Msg  string                `json:"msg"`
	Data GetTokenByAuthResData `json:"data"`
}

type GetTokenByRefreshTokenReq struct {
	RefreshToken string `form:"refresh_token"`
}

type GetTokenByRefreshTokenResData struct {
	Oauth2Token interface{} `json:"oauth2_token"`
}

type GetTokenByRefreshTokenRes struct {
	Code uint32                        `json:"code"`
	Msg  string                        `json:"msg"`
	Data GetTokenByRefreshTokenResData `json:"data"`
}

type ReadTokenReq struct {
	TokenType  string `form:"token_type"`
	TokenValue string `form:"token_value"`
}

type ReadTokenResData struct {
	Payload string `json:"payload"`
}

type ReadTokenRes struct {
	Code uint32           `json:"code"`
	Msg  string           `json:"msg"`
	Data ReadTokenResData `json:"data"`
}
