// Code generated by goctl. DO NOT EDIT!
// Source: user.sys.proto

package server

import (
	"context"
	"douyin/app/common/log"
	"go.uber.org/zap"

	"douyin/app/service/user/rpc/sys/internal/logic"
	"douyin/app/service/user/rpc/sys/internal/svc"
	"douyin/app/service/user/rpc/sys/pb"
)

type SysServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSysServer
}

func NewSysServer(svcCtx *svc.ServiceContext) *SysServer {
	return &SysServer{
		svcCtx: svcCtx,
	}
}

func (s *SysServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterRes, error) {
	log.Logger.Debug("recv:", zap.String("msg", in.String()))
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	res, err := l.Register(in)
	log.Logger.Debug("send:", zap.String("msg", res.String()))
	return res, err
}

func (s *SysServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginRes, error) {
	log.Logger.Debug("recv:", zap.String("msg", in.String()))
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	res, err := l.Login(in)
	log.Logger.Debug("send:", zap.String("msg", res.String()))
	return res, err
}
